# -*- coding: utf-8 -*-
"""VLM_Remote_Sensing_classification (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ljJt1f9uh0L_2dfLkK_rKwChxhvdLEsD
"""

import os
os.environ['KAGGLE_API_TOKEN'] = 'YOUR_KEY_HERE'

!pip install -U kaggle

# Download EuroSAT
!kaggle datasets download -d apollo2506/eurosat-dataset

# Unzip in current directory
!unzip -q eurosat-dataset.zip -d .

# Download NWPU-RESISC45
!kaggle datasets download -d aqibrehmanpirzada/nwpuresisc45

# Unzip in current directory
!unzip -q nwpuresisc45.zip -d .

"""**Imports**"""

import os
import random
import torch
import numpy as np

from PIL import Image
from tqdm import tqdm

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

import matplotlib.pyplot as plt
import seaborn as sns

"""**Dataset Classes**"""

EUROSAT_CLASSES = [
    "River",
    "Forest",
    "Residential",
    "AnnualCrop",
]

NWPU_SUBSET = [
    "airport",
    "beach",
    "forest",
    "harbor",
    "stadium"
]

"""**Prompt Pools**"""

BLIP2_PROMPTS = [

    """
    Question: Which class best describes this satellite image?
    Choices: {labels}
    Answer with only one class name.
    """,

    """
    Question: Identify the land-use category in this remote sensing image.
    Options: {labels}
    Respond using one label only.
    """,

    """
    Question: This aerial image belongs to which category?
    Classes: {labels}
    Only output the class name.
    """,

    """
    Question: What is the correct scene category for this satellite image?
    Candidate labels: {labels}
    Answer using exactly one label.
    """,

    """
    Question: Analyze this remote sensing image and determine its class.
    Available classes: {labels}
    Return only the predicted category.
    """,

    """
    Question: Which land-cover type is shown in this aerial image?
    Labels: {labels}
    Respond with a single class name only.
    """,

    """
    Question: Select the most appropriate category for this satellite scene.
    Categories: {labels}
    Output only one category.
    """,

    """
    Question: What environment or land-use class is represented in this image?
    Possible labels: {labels}
    Answer with one label only.
    """,

    """
    Question: Determine the scene classification of this remote sensing image.
    Classes available: {labels}
    Provide only the class name.
    """,

    """
    Question: Classify this Earth observation image.
    Choices are: {labels}
    Return exactly one class label.
    """,

    """
    Question: Which category best matches the content of this aerial photograph?
    Options: {labels}
    Respond with only one option.
    """,

    """
    Question: Predict the land-use classification for this satellite image.
    Candidate categories: {labels}
    Give only one category name.
    """,

    """
    Question: Identify the scene type shown in this remote sensing image.
    Possible classes: {labels}
    Return one label only.
    """,

    """
    Question: Which label correctly describes this Earth surface image?
    Labels: {labels}
    Answer using a single label only.
    """,

    """
    Question: Assign this satellite image to the correct category.
    Available options: {labels}
    Only provide the class name.
    """,

    """
    Question: What type of scene is visible in this aerial image?
    Candidate labels: {labels}
    Respond with one category only.
    """,

    """
    Question: Choose the correct remote sensing category for this image.
    Categories: {labels}
    Output one label only.
    """,

    """
    Question: Identify the dominant land-use class in this image.
    Possible answers: {labels}
    Return a single class label.
    """,

    """
    Question: What is the most likely classification of this satellite image?
    Choices: {labels}
    Give only one answer.
    """,

    """
    Question: Determine which category this remote sensing image belongs to.
    Labels available: {labels}
    Respond with only the category name.
    """
]

LLAVA_PROMPTS = [

    """
    USER: <image>
    Which class best describes this satellite image?
    Choices: {labels}
    Answer with one class only.
    ASSISTANT:
    """,

    """
    USER: <image>
    Identify the remote sensing category.
    Options: {labels}
    Return only one label.
    ASSISTANT:
    """,

    """
    USER: <image>
    Classify this aerial image into one category:
    {labels}
    ASSISTANT:
    """,

    """
    USER: <image>
    What is the correct scene category for this satellite image?
    Candidate labels: {labels}
    Answer using exactly one label.
    ASSISTANT:
    """,

    """
    USER: <image>
    Analyze this remote sensing image and determine its class.
    Available classes: {labels}
    Return only the predicted category.
    ASSISTANT:
    """,

    """
    USER: <image>
    Which land-cover type is shown in this aerial image?
    Labels: {labels}
    Respond with a single class name only.
    ASSISTANT:
    """,

    """
    USER: <image>
    Select the most appropriate category for this satellite scene.
    Categories: {labels}
    Output only one category.
    ASSISTANT:
    """,

    """
    USER: <image>
    What environment or land-use class is represented in this image?
    Possible labels: {labels}
    Answer with one label only.
    ASSISTANT:
    """,

    """
    USER: <image>
    Determine the scene classification of this remote sensing image.
    Classes available: {labels}
    Provide only the class name.
    ASSISTANT:
    """,

    """
    USER: <image>
    Classify this Earth observation image.
    Choices are: {labels}
    Return exactly one class label.
    ASSISTANT:
    """,

    """
    USER: <image>
    Which category best matches the content of this aerial photograph?
    Options: {labels}
    Respond with only one option.
    ASSISTANT:
    """,

    """
    USER: <image>
    Predict the land-use classification for this satellite image.
    Candidate categories: {labels}
    Give only one category name.
    ASSISTANT:
    """,

    """
    USER: <image>
    Identify the scene type shown in this remote sensing image.
    Possible classes: {labels}
    Return one label only.
    ASSISTANT:
    """,

    """
    USER: <image>
    Which label correctly describes this Earth surface image?
    Labels: {labels}
    Answer using a single label only.
    ASSISTANT:
    """,

    """
    USER: <image>
    Assign this satellite image to the correct category.
    Available options: {labels}
    Only provide the class name.
    ASSISTANT:
    """,

    """
    USER: <image>
    What type of scene is visible in this aerial image?
    Candidate labels: {labels}
    Respond with one category only.
    ASSISTANT:
    """,

    """
    USER: <image>
    Choose the correct remote sensing category for this image.
    Categories: {labels}
    Output one label only.
    ASSISTANT:
    """,

    """
    USER: <image>
    Identify the dominant land-use class in this image.
    Possible answers: {labels}
    Return a single class label.
    ASSISTANT:
    """,

    """
    USER: <image>
    What is the most likely classification of this satellite image?
    Choices: {labels}
    Give only one answer.
    ASSISTANT:
    """,

    """
    USER: <image>
    Determine which category this remote sensing image belongs to.
    Labels available: {labels}
    Respond with only the category name.
    ASSISTANT:
    """
]

EUROSAT_PATH = "EuroSAT"

plt.figure(figsize=(16, 4))

for i, class_name in enumerate(EUROSAT_CLASSES):

    class_dir = os.path.join(EUROSAT_PATH, class_name)

    image_name = random.choice(os.listdir(class_dir))

    image_path = os.path.join(class_dir, image_name)

    image = Image.open(image_path)

    plt.subplot(1, 4, i + 1)

    plt.imshow(image)

    plt.title(class_name,fontsize=20)

    plt.axis("off")

plt.tight_layout()

plt.show()

NWPU_PATH = "Dataset/test/test"

plt.figure(figsize=(20, 4))

for i, class_name in enumerate(NWPU_SUBSET):

    class_dir = os.path.join(NWPU_PATH, class_name)

    image_name = random.choice(os.listdir(class_dir))

    image_path = os.path.join(class_dir, image_name)

    image = Image.open(image_path)

    plt.subplot(1, 5, i + 1)

    plt.imshow(image)

    plt.title(class_name, fontsize=22)

    plt.axis("off")

plt.tight_layout()

plt.show()

"""**Dataset Loader**"""

def load_dataset(dataset_path, labels, percentage=10):

    samples = []

    # normalize labels for matching
    normalized_labels = {
        label.lower(): label
        for label in labels
    }

    for folder_name in os.listdir(dataset_path):

        class_dir = os.path.join(dataset_path, folder_name)

        if not os.path.isdir(class_dir):
            continue

        # normalize folder name
        normalized_folder = folder_name.lower().strip()

        # skip folders not in labels list
        if normalized_folder not in normalized_labels:
            continue

        # use official label name from labels list
        class_name = normalized_labels[normalized_folder]

        class_samples = []

        for image_name in os.listdir(class_dir):

            image_path = os.path.join(class_dir, image_name)

            class_samples.append((image_path, class_name))

        # shuffle class images
        random.shuffle(class_samples)

        # select x%
        num_samples = int(
            len(class_samples) * (percentage / 100)
        )

        # keep subset
        class_samples = class_samples[:num_samples]

        samples.extend(class_samples)

    # shuffle final dataset
    random.shuffle(samples)

    return samples

def evaluate_model(y_true, y_pred, labels, model_name,dataset_name):

    accuracy = accuracy_score(y_true, y_pred)

    precision = precision_score(
        y_true,
        y_pred,
        average="weighted",
        zero_division=0
    )

    recall = recall_score(
        y_true,
        y_pred,
        average="weighted",
        zero_division=0
    )

    f1 = f1_score(
        y_true,
        y_pred,
        average="weighted",
        zero_division=0
    )

    print(f"\n===== {model_name} =====")

    print(f"Accuracy  : {accuracy:.4f}")
    print(f"Precision : {precision:.4f}")
    print(f"Recall    : {recall:.4f}")
    print(f"F1-score  : {f1:.4f}")

    print("\nClassification Report:\n")

    print(classification_report(y_true, y_pred))

    cm = confusion_matrix(
        y_true,
        y_pred,
        labels=labels
    )

    plt.figure(figsize=(10, 8))

    ax = sns.heatmap(
        cm,
        annot=True,
        fmt="d",
        xticklabels=labels,
        yticklabels=labels,
        annot_kws={"size": 25}   # values inside boxes
    )

    # Title font size
    plt.title(f"{model_name} Confusion Matrix on {dataset_name}", fontsize=20)

    # Axis label font sizes
    plt.xlabel("Predicted", fontsize=20)
    plt.ylabel("Actual", fontsize=20)

    # Class names font sizes
    plt.xticks(fontsize=16)
    plt.yticks(fontsize=16)

    plt.show()

import re

def format_label(label):

    # convert CamelCase -> space separated
    label = re.sub(r'(?<!^)(?=[A-Z])', ' ', label)

    # replace separators
    label = label.replace("_", " ")
    label = label.replace("-", " ")
    label = label.replace("/", " ")

    # lowercase
    label = label.lower()

    # remove extra spaces
    label = " ".join(label.split())

    return label

"""**Initialize CLIP**"""

from transformers import pipeline

clip_model = pipeline(
    task="zero-shot-image-classification",
    model="openai/clip-vit-base-patch32",
    device=0
)

def classify_clip(dataset_path, labels,dataset_name="", percentage=10):

    samples = load_dataset(dataset_path,labels,percentage)

    y_true = []
    y_pred = []

    for image_path, actual_label in tqdm(samples):

        result = clip_model(
            image_path,
            candidate_labels=labels
        )

        prediction = result[0]["label"]

        y_true.append(actual_label)
        y_pred.append(prediction)

    evaluate_model(
        y_true,
        y_pred,
        labels,
        "CLIP",
        dataset_name
    )

"""**Run CLIP**"""

classify_clip(
    "EuroSAT",
    EUROSAT_CLASSES,
    dataset_name="EuroSAT",
    percentage=10
)

classify_clip(
    "Dataset/train/train",
    NWPU_SUBSET,
    dataset_name="NWPU",
    percentage=20
)

"""**Initialize BLIP-2**"""

from transformers import (
    Blip2Processor,
    Blip2ForConditionalGeneration
)

blip2_processor = Blip2Processor.from_pretrained(
    "Salesforce/blip2-flan-t5-xl"
)

blip2_model = Blip2ForConditionalGeneration.from_pretrained(
    "Salesforce/blip2-flan-t5-xl",
    torch_dtype=torch.float16,
    device_map="auto"
)

def classify_blip2(dataset_path, labels,dataset_name="", percentage=10):

    samples = load_dataset(
        dataset_path,
        labels,
        percentage
    )

    y_true = []
    y_pred = []

    labels_text = ", ".join((labels))
    labels_text = format_label(labels_text)
    for image_path, actual_label in tqdm(samples):

        image = Image.open(image_path).convert("RGB")

        # random prompt
        prompt_template = random.choice(BLIP2_PROMPTS)

        prompt = prompt_template.format(
            labels=labels_text
        )

        # preprocess
        inputs = blip2_processor(
            images=image,
            text=prompt,
            return_tensors="pt"
        ).to(blip2_model.device)

        # generate
        generated_ids = blip2_model.generate(
            **inputs,
            max_new_tokens=15,
        )

        # decode
        prediction = blip2_processor.batch_decode(
            generated_ids,
            skip_special_tokens=True
        )[0].strip()

        #print("\nraw prediction:", prediction)

        # normalized prediction
        normalized_prediction = (
            prediction.lower()
            .replace(" ", "")
            .replace("_", "")
            .replace("-", "")
            .replace("/", "")
        )

        matched_labels = []

        # search all labels
        for label in labels:

            normalized_label = (
                label.lower()
                .replace(" ", "")
                .replace("_", "")
                .replace("-", "")
                .replace("/", "")
            )

            if normalized_label in normalized_prediction:

                matched_labels.append(label)

        # choose best match
        if actual_label in matched_labels:

            matched_label = actual_label

        elif len(matched_labels) > 0:

            matched_label = matched_labels[0]

        else:

            matched_label = "Unknown"

        #print("matched labels:", matched_labels)
        #print("final predicted:", matched_label)
        #print("actual:", actual_label)
        #print("correct:", matched_label == actual_label)

        y_true.append(actual_label)
        y_pred.append(matched_label)

    evaluate_model(
        y_true,
        y_pred,
        labels,
        "BLIP-2",
        dataset_name
    )

"""**Run BLIP-2**"""

classify_blip2(
    "EuroSAT",
    EUROSAT_CLASSES,
    dataset_name="EuroSAT",
    percentage=10
)

classify_blip2(
    "Dataset/train/train",
    NWPU_SUBSET,
    dataset_name="NWPU",
    percentage=20
)

"""**Initialize LLaVA**"""

from transformers import (
    AutoProcessor,
    LlavaForConditionalGeneration
)

model_id = "llava-hf/llava-1.5-7b-hf"

llava_processor = AutoProcessor.from_pretrained(
    model_id
)

llava_model = LlavaForConditionalGeneration.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    device_map="auto"
)

def classify_llava(dataset_path, labels,dataset_name="", percentage=10):

    samples = load_dataset(dataset_path,labels, percentage)

    y_true = []
    y_pred = []

    labels_text = ", ".join(labels)
    labels_text = format_label(labels_text)
    for image_path, actual_label in tqdm(samples):

        image = Image.open(image_path).convert("RGB")

        prompt_template = random.choice(LLAVA_PROMPTS)

        prompt = prompt_template.format(
            labels=labels_text
        )

        inputs = llava_processor(
            text=prompt,
            images=image,
            return_tensors="pt"
        ).to(llava_model.device, torch.float16)

        output = llava_model.generate(
            **inputs,
            max_new_tokens=20
        )

        result = llava_processor.decode(
            output[0],
            skip_special_tokens=True
        )

        matched_label = "Unknown"

        if "ASSISTANT:" in result:
            result = result.split("ASSISTANT:")[-1]

        for label in labels:

            if label.lower() in result.lower():

                matched_label = label
                break

        y_true.append(actual_label)
        y_pred.append(matched_label)

    evaluate_model(
        y_true,
        y_pred,
        labels,
        "LLaVA",
        dataset_name
    )

"""**Run LLaVA**"""

classify_llava(
    "EuroSAT",
    EUROSAT_CLASSES,
    dataset_name="EuroSAT",
    percentage=10
)

classify_llava(
    "Dataset/train/train",
    NWPU_SUBSET,
    dataset_name="NWPU",
    percentage=20
)

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

# Paths to your 6 images
image_paths = [
    "clip_eurosat.png", "clip_nwpu.png", "blip2_eurosat.png",
    "blip2_nwpu.png", "llava_eurosat.png", "llava_nwpu.png"
]

# Captions
captions = ['a', 'b', 'c', 'd', 'e', 'f']

# 2 rows, 3 columns
fig, axes = plt.subplots(2, 3, figsize=(12, 7))

# Small horizontal & vertical spacing
plt.subplots_adjust(wspace=0.01, hspace=0.01)

for i, ax in enumerate(axes.flat):
    img = mpimg.imread(image_paths[i])

    ax.imshow(img)
    ax.axis('off')

    # Caption below image
    ax.text(
        0.5, -0.03,
        f"({captions[i]})",
        transform=ax.transAxes,
        ha='center',
        va='top',
        fontsize=0
    )

# Tight layout with small padding
plt.tight_layout(pad=0.3)

plt.show()